package ru.novikov.novikovthetvdb.Model.DataBase.GreenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FAVORITE_ITEM".
 */
public class FavoriteItem {

    private Long id;
    private String owner;
    private Long seriesId;
    private String seriesName;
    private String genre;

    public FavoriteItem() {
    }

    public FavoriteItem(Long id) {
        this.id = id;
    }

    public FavoriteItem(Long id, String owner, Long seriesId, String seriesName, String genre) {
        this.id = id;
        this.owner = owner;
        this.seriesId = seriesId;
        this.seriesName = seriesName;
        this.genre = genre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Long getSeriesId() {
        return seriesId;
    }

    public void setSeriesId(Long seriesId) {
        this.seriesId = seriesId;
    }

    public String getSeriesName() {
        return seriesName;
    }

    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

}
